services:
  minecraft-gtnh:
    build:
      context: .
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: 'true'
      SEED: '1293967824733727157'
      DIFFICULTY: '2'
      MOTD: 'My GT:NH Server'
      VIEW_DISTANCE: '32'

    volumes:
      - ./data/whitelist.json:/minecraft/whitelist.json:ro
      - ./data/ops.json:/minecraft/ops.json:ro
      - mc-world:/minecraft/World
      - mc-backups:/minecraft/backups

volumes:
  mc-world:
  mc-backups:
