services:
  minecraft-gtnh:
    image: ghcr.io/istoleyurballs/minecraft-gtnh:latest
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: 'true'
      SEED: '1293967824733727157'
      DIFFICULTY: '2'
      MOTD: 'My GT:NH Server'
      VIEW_DISTANCE: '4'

    volumes:
      - mc-world:/minecraft/World
      - mc-journeymap:/minecraft/config/JourneyMapServer
      - mc-logs:/minecraft/logs
      # - ./data/server-icon.png:/minecraft/server-icon.png:ro
      - ./data/whitelist.json:/minecraft/whitelist.json
      - ./data/ops.json:/minecraft/ops.json
      # - ./data/banned-players:/minecraft/banned-players.json
      # - ./data/banned-ips:/minecraft/banned-ips.json
      - mc-backups:/minecraft/backups

volumes:
  # Ideally they would use the subpath functionnality of a single volume but i won't bother for the example
  mc-world:
  mc-journeymap:
  mc-logs:
  mc-backups:
